#!/usr/bin/env bash
set -euo pipefail

# Minimal disposable gradlew replacement that downloads a specific Gradle distribution
# and runs it. This gives CI and contributors a stable ./gradlew entrypoint without
# requiring the gradle-wrapper.jar to be committed.
# NOTE: This is intentionally simple; prefer committing the official Gradle wrapper
# (gradle/wrapper/* and gradlew.bat) generated by `gradle wrapper` in the long term.

GRADLE_VERSION="8.4"
CACHE_BASE="${HOME}/.gradle/wrapper/dists/gradle-${GRADLE_VERSION}-bin"
GRADLE_HOME="$CACHE_BASE/gradle-${GRADLE_VERSION}"

if [ ! -x "$GRADLE_HOME/bin/gradle" ]; then
  mkdir -p "$CACHE_BASE"
  ZIPPATH="/tmp/gradle-${GRADLE_VERSION}-bin.zip"
  if [ ! -f "$ZIPPATH" ]; then
    echo "Downloading Gradle ${GRADLE_VERSION}..."
    curl -fsSL -o "$ZIPPATH" "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
  fi
  echo "Unpacking Gradle to $CACHE_BASE"
  unzip -q -o "$ZIPPATH" -d "$CACHE_BASE"
fi

exec "$GRADLE_HOME/bin/gradle" "$@"
